

DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT(
  id INTEGER auto_increment PRIMARY KEY,
  name VARCHAR(50)
);

DROP TABLE IF EXISTS PROJECT;
CREATE TABLE PROJECT(
  id INTEGER auto_increment PRIMARY KEY,
  name VARCHAR(50)
);

DROP TABLE IF EXISTS COLLABORATOR;
CREATE TABLE COLLABORATOR(
  id INTEGER auto_increment PRIMARY KEY,
  departmentId INTEGER,
  name VARCHAR(50),
  type VARCHAR(1),
CONSTRAINT FK_COLLAB_DEPT FOREIGN KEY (departmentId) REFERENCES DEPARTMENT(id)
);

DROP TABLE IF EXISTS COLLAB_PROJECT;
CREATE TABLE COLLAB_PROJECT(
  collaboratorId INTEGER PRIMARY KEY,
  projectId INTEGER,
  CONSTRAINT FK_COLLAB_PROJECT FOREIGN KEY (collaboratorId) REFERENCES COLLABORATOR(id)
);

DROP TABLE IF EXISTS MANAGER_PROJECT;
CREATE TABLE MANAGER_PROJECT(
  collaboratorId INTEGER,
  projectId INTEGER PRIMARY KEY,
  CONSTRAINT FK_MANAGER_PROJECT FOREIGN KEY (projectId) REFERENCES PROJECT(id),
  CONSTRAINT FK_MANAGER_PROJECT2 FOREIGN KEY (collaboratorId) REFERENCES COLLABORATOR(id)
);


