INSERT INTO DEPARTMENT VALUES (DEFAULT, 'SALES');
INSERT INTO DEPARTMENT VALUES (DEFAULT, 'HUMAN RESOURCES');
INSERT INTO DEPARTMENT VALUES (DEFAULT, 'MARKETING');
INSERT INTO DEPARTMENT VALUES (DEFAULT, 'IT');
INSERT INTO DEPARTMENT VALUES (DEFAULT, 'RESEARCH');

INSERT INTO PROJECT VALUES (DEFAULT, 'BRADESCO');
INSERT INTO PROJECT VALUES (DEFAULT, 'RAIZEN');
INSERT INTO PROJECT VALUES (DEFAULT, 'SANOFI');
INSERT INTO PROJECT VALUES (DEFAULT, 'MAPFRE');
INSERT INTO PROJECT VALUES (DEFAULT, 'SULAMERICA');
INSERT INTO PROJECT VALUES (DEFAULT, 'SANTANDER');
INSERT INTO PROJECT VALUES (DEFAULT, 'ZURICH');
INSERT INTO PROJECT VALUES (DEFAULT, 'SODEXO');
INSERT INTO PROJECT VALUES (DEFAULT, 'SCHNEIDER');
INSERT INTO PROJECT VALUES (DEFAULT, 'COCA-COLA');

INSERT INTO COLLABORATOR VALUES (DEFAULT, 1, 'ED FIRINO', 'M');
INSERT INTO COLLABORATOR VALUES (DEFAULT, 2, 'JACOB ALYSON', 'R');
INSERT INTO COLLABORATOR VALUES (DEFAULT, 3, 'ANTHONY HOPKINS', 'R');
INSERT INTO COLLABORATOR VALUES (DEFAULT, 4, 'THALES OF MILETUS', 'M');
INSERT INTO COLLABORATOR VALUES (DEFAULT, 5, 'LEONARDO DA VINCI', 'M');
INSERT INTO COLLABORATOR VALUES (DEFAULT, 3, 'ZEUS', 'R');
INSERT INTO COLLABORATOR VALUES (DEFAULT, 4, 'NEO', 'R');
INSERT INTO COLLABORATOR VALUES (DEFAULT, 2, 'SAURON', 'R');
INSERT INTO COLLABORATOR VALUES (DEFAULT, 1, 'GANDALF', 'R');
INSERT INTO COLLABORATOR VALUES (DEFAULT, 5, 'EZIO AUDITORE DA FIRENZE', 'R');

INSERT INTO COLLAB_PROJECT VALUES (2,1);
INSERT INTO COLLAB_PROJECT VALUES (3,2);
INSERT INTO COLLAB_PROJECT VALUES (6,7);
INSERT INTO COLLAB_PROJECT VALUES (7,7);
INSERT INTO COLLAB_PROJECT VALUES (8,5);
INSERT INTO COLLAB_PROJECT VALUES (9,8);
INSERT INTO COLLAB_PROJECT VALUES (10,10);

INSERT INTO MANAGER_PROJECT VALUES (1,1);
INSERT INTO MANAGER_PROJECT VALUES (1,2);
INSERT INTO MANAGER_PROJECT VALUES (1,3);
INSERT INTO MANAGER_PROJECT VALUES (1,4);
INSERT INTO MANAGER_PROJECT VALUES (4,5);
INSERT INTO MANAGER_PROJECT VALUES (4,6);
INSERT INTO MANAGER_PROJECT VALUES (5,7);
INSERT INTO MANAGER_PROJECT VALUES (5,8);
INSERT INTO MANAGER_PROJECT VALUES (5,9);
INSERT INTO MANAGER_PROJECT VALUES (4,10);